apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  frontend
spec:
  tls:
  - hosts: 
    - ENV.k8s.mevijay.com 
    secretName: wildcard
  rules:
  - host: ENV.k8s.mevijay.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /
